# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_matrix <- function(matrix) {
    invisible(.Call('_sparseMatrixStats_print_matrix', PACKAGE = 'sparseMatrixStats', matrix))
}

subset_sum <- function(v, start, end) {
    .Call('_sparseMatrixStats_subset_sum', PACKAGE = 'sparseMatrixStats', v, start, end)
}

subset_sum_without_na <- function(v, start, end) {
    .Call('_sparseMatrixStats_subset_sum_without_na', PACKAGE = 'sparseMatrixStats', v, start, end)
}

matrix_subset_sum <- function(matrix, start, end) {
    .Call('_sparseMatrixStats_matrix_subset_sum', PACKAGE = 'sparseMatrixStats', matrix, start, end)
}

